// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbrmimjesegdcqlfsuem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxicm1pbWplc2VnZGNxbGZzdWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTYwNTksImV4cCI6MjA2Mjk5MjA1OX0.OjLNLSnfTI8lUACIzKLdGksGT9Vhu5uaAcdfxGngd0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);